//////////////////////////////////////////////////////////////
// This file is generated from the Minecraft documentation. //
// DO NOT EDIT THIS FILE! YOUR CHANGES WILL BE OVERWRITTEN! //
//////////////////////////////////////////////////////////////

/// <reference path="./server_component_names.generated.d.ts" />
/// <reference path="./server_component.generated.d.ts" />

declare interface IVanillaServerSystemBase {
    createComponent(entity: IEntity, componentName: MinecraftComponent.ArmorContainer): IComponent<IArmorContainerComponent> | null;
    createComponent(entity: IEntity, componentName: MinecraftComponent.Attack): IComponent<IAttackComponent> | null;
    createComponent(entity: IEntity, componentName: MinecraftComponent.CollisionBox): IComponent<ICollisionBoxComponent> | null;
    createComponent(entity: IEntity, componentName: MinecraftComponent.DamageSensor): IComponent<IDamageSensorComponent> | null;
    createComponent(entity: IEntity, componentName: MinecraftComponent.Equipment): IComponent<IEquipmentComponent> | null;
    createComponent(entity: IEntity, componentName: MinecraftComponent.Equippable): IComponent<IEquippableComponent> | null;
    createComponent(entity: IEntity, componentName: MinecraftComponent.Explode): IComponent<IExplodeComponent> | null;
    createComponent(entity: IEntity, componentName: MinecraftComponent.HandContainer): IComponent<IHandContainerComponent> | null;
    createComponent(entity: IEntity, componentName: MinecraftComponent.Healable): IComponent<IHealableComponent> | null;
    createComponent(entity: IEntity, componentName: MinecraftComponent.Health): IComponent<IHealthComponent> | null;
    createComponent(entity: IEntity, componentName: MinecraftComponent.HotbarContainer): IComponent<IHotbarContainerComponent> | null;
    createComponent(entity: IEntity, componentName: MinecraftComponent.Interact): IComponent<IInteractComponent> | null;
    createComponent(entity: IEntity, componentName: MinecraftComponent.Inventory): IComponent<IInventoryComponent> | null;
    createComponent(entity: IEntity, componentName: MinecraftComponent.InventoryContainer): IComponent<IInventoryContainerComponent> | null;
    createComponent(entity: IEntity, componentName: MinecraftComponent.LookAt): IComponent<ILookAtComponent> | null;
    createComponent(entity: IEntity, componentName: MinecraftComponent.Nameable): IComponent<INameableComponent> | null;
    createComponent(entity: IEntity, componentName: MinecraftComponent.Position): IComponent<IPositionComponent> | null;
    createComponent(entity: IEntity, componentName: MinecraftComponent.Rotation): IComponent<IRotationComponent> | null;
    createComponent(entity: IEntity, componentName: MinecraftComponent.Shooter): IComponent<IShooterComponent> | null;
    createComponent(entity: IEntity, componentName: MinecraftComponent.SpawnEntity): IComponent<ISpawnEntityComponent> | null;
    createComponent(entity: IEntity, componentName: MinecraftComponent.Teleport): IComponent<ITeleportComponent> | null;
    createComponent(entity: IEntity, componentName: MinecraftComponent.TickWorld): IComponent<ITickWorldComponent> | null;

    getComponent(entity: IEntity, componentName: MinecraftComponent.ArmorContainer): IComponent<IArmorContainerComponent> | null;
    getComponent(entity: IEntity, componentName: MinecraftComponent.Attack): IComponent<IAttackComponent> | null;
    getComponent(entity: IEntity, componentName: MinecraftComponent.CollisionBox): IComponent<ICollisionBoxComponent> | null;
    getComponent(entity: IEntity, componentName: MinecraftComponent.DamageSensor): IComponent<IDamageSensorComponent> | null;
    getComponent(entity: IEntity, componentName: MinecraftComponent.Equipment): IComponent<IEquipmentComponent> | null;
    getComponent(entity: IEntity, componentName: MinecraftComponent.Equippable): IComponent<IEquippableComponent> | null;
    getComponent(entity: IEntity, componentName: MinecraftComponent.Explode): IComponent<IExplodeComponent> | null;
    getComponent(entity: IEntity, componentName: MinecraftComponent.HandContainer): IComponent<IHandContainerComponent> | null;
    getComponent(entity: IEntity, componentName: MinecraftComponent.Healable): IComponent<IHealableComponent> | null;
    getComponent(entity: IEntity, componentName: MinecraftComponent.Health): IComponent<IHealthComponent> | null;
    getComponent(entity: IEntity, componentName: MinecraftComponent.HotbarContainer): IComponent<IHotbarContainerComponent> | null;
    getComponent(entity: IEntity, componentName: MinecraftComponent.Interact): IComponent<IInteractComponent> | null;
    getComponent(entity: IEntity, componentName: MinecraftComponent.Inventory): IComponent<IInventoryComponent> | null;
    getComponent(entity: IEntity, componentName: MinecraftComponent.InventoryContainer): IComponent<IInventoryContainerComponent> | null;
    getComponent(entity: IEntity, componentName: MinecraftComponent.LookAt): IComponent<ILookAtComponent> | null;
    getComponent(entity: IEntity, componentName: MinecraftComponent.Nameable): IComponent<INameableComponent> | null;
    getComponent(entity: IEntity, componentName: MinecraftComponent.Position): IComponent<IPositionComponent> | null;
    getComponent(entity: IEntity, componentName: MinecraftComponent.Rotation): IComponent<IRotationComponent> | null;
    getComponent(entity: IEntity, componentName: MinecraftComponent.Shooter): IComponent<IShooterComponent> | null;
    getComponent(entity: IEntity, componentName: MinecraftComponent.SpawnEntity): IComponent<ISpawnEntityComponent> | null;
    getComponent(entity: IEntity, componentName: MinecraftComponent.Teleport): IComponent<ITeleportComponent> | null;
    getComponent(entity: IEntity, componentName: MinecraftComponent.TickWorld): IComponent<ITickWorldComponent> | null;

    /**
     * Creates a component of the specified name and adds it to the entity. This should only be used with custom components which need 
     * to be registered first. If the entity already has the component, this will retrieve the component already there instead.
     * @param entity The EntityObject that was retrieved from a call to createEntity() or retrieved from an event
     * @param componentName The name of the component to add to the entity. This is either the name of a built-in component (check the Script Components section) or a custom component created with a call to registerComponent()
     * @returns An object with all the fields as defined in the component, or null if something went wrong when creating the component
     */
    createComponent<TComponent>(entity: IEntity, componentName: string): IComponent<TComponent> | null;

    /**
     * Looks for the specified component in the entity. If it exists, retrieves the data from the component and returns it.
     * @param entity The EntityObject that was retrieved from a call to createEntity() or retrieved from an event
     * @param componentIdentifier The name of the component to retrieve from the entity. This is either the name of a built-in component (check the Script Components section) or a custom component created with a call to registerComponent()
     * @returns An object containing the data of the component as described in the component itself, or null if the entity did not have the component or something went wrong when getting the component
     */
    getComponent<TComponent>(entity: IEntity, componentIdentifier: MinecraftComponent | string): IComponent<TComponent> | null;
}
